= Hibernate standalone test app

Hibernate standalone test application using Hibernate api to generate database schema
and then persist and query an item.

== How to run

== Getting run a database

Download jdbc driver (e.g. for PostgreSQL, see https://jdbc.postgresql.org/download.html) and run the database itself.
The easiest way is probably with Docker

```bash
docker run -p 5432:5432 --rm  -ePOSTGRES_USER=test -e POSTGRES_PASSWORD=test postgres:9.4 -c max-prepared-transactions=110 -c log-statement=all
```

== Run the app

If your database is running at different machine than at `localhost:5432` or with different credentials than `test/test`
then consider to make changes in `src/main/resources/persistence.xml`.

```bash
mvn clean package
java -cp target/hibernate-standalone-1.0-SNAPSHOT-jar-with-dependencies.jar:./postgresql-42.2.2.jar:. cz.chalda.Main
```
java -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=y -Dproperties.file=./setup.properties -Ddb.table.name=ttt -cp /home/ochaloup/conn/postgresql-42.2.2.jar:target/txn-recovery-marker-jdbc-1.0-SNAPSHOT-jar-with-dependencies.jar org.jboss.openshift.Main
